export const DEFAULT_CHARACTER_ID = "furina";

export const characters = {
  furina: {
    id: "furina",
    displayName: "Furina",
    element: "Hydro · Fontaine",
    title: "Hydro Archon of Fontaine",
    description:
      "화려한 박수 소리 한가운데에서도, 진짜 마음은 조용히 숨겨두는 소녀. 푸리나의 반짝임과 여린 진심을 함께 보여주는 페이지입니다.",
    profileText:
      "푸리나는 물 원소를 사용하는 5성 한손검 캐릭터로, 팀 전체를 안정적으로 도와주는 역할에 강점이 있습니다. 스토리에서는 화려한 무대 뒤에 숨겨진 솔직한 마음이 큰 매력으로 남아요.",
    pills: ["Hydro", "5★", "Sword", "Fontaine"],
    stats: [
      ["역할", "팀을 돕는 하이드로 서포터"],
      ["무기", "한손검 (Sword)"],
      ["매력 포인트", "화려함 뒤의 다정한 진심"],
    ],
    snapshot: {
      kicker: "Combat Snapshot",
      heading: "Team Utility Focus",
      summary:
        "푸리나는 파티 전반의 안정감과 화력을 함께 끌어올리는 지원형 운영에 강합니다. 전투 템포를 끊지 않고 계속 이어주는 플레이가 핵심입니다.",
      points: [
        ["강점", "파티 전체 흐름 유지 + 안정적 지원"],
        ["추천 반응", "Hydro 기반 증발/감전 조합"],
        ["운영 팁", "교체 타이밍을 짧게 가져가며 순환 유지"],
      ],
      tags: ["Support Core", "Smooth Rotation", "Hydro Utility"],
    },
    terminal: {
      title: "Furina Deep Scan Console",
      prompt: "furina@fontaine:~$",
      bridgeCaption: "Fontaine Archive · Curtain Call",
      fileLabel: "FURINA_LINEART.ASC",
      checksum: "5F-A9-2D-FF",
      bootLogs: [
        "[BOOT] Combat Snapshot uplink accepted",
        "[SYNC] Region profile loaded: Fontaine",
        "[LOAD] Queue: portrait, mapline, keyword-banner",
        "[DECODE] Runtime profile: balanced",
        "[READY] ASCII channel online",
      ],
      assets: {
        portrait: "./ImageReference/Furina/Png/LineArt.png",
        mapline: "./ImageReference/Furina/Png/MapLine.jpg",
      },
      sequence: ["portrait", "mapline", "portrait", "mapline"],
      sceneLabels: {
        portrait: "FURINA_PORTRAIT.ASC",
        mapline: "FONTAINE_MAPLINE.ASC",
        banner: "FONTAINE_SIGNAL.ASC",
      },
      banners: ["FONTAINE", "HYDRO", "SALON SOLITAIRE"],
      tabs: {
        "boot.log": [
          "Session: FURINA TERMINAL V3",
          "Node: Opera Epiclese relay",
          "Protocol: Hydro-Luma stream",
          "Status: Decode-ready",
        ],
        "ascii.feed": [
          "Charset: .,:;=+*#%@",
          "Sampling: 124 cols / adaptive rows",
          "Edge blend: 32%",
          "Glitch budget: LOW (cinematic safe)",
        ],
        "dossier.sys": [
          "Name: Furina",
          "Element: Hydro · Fontaine",
          "Role: Team Utility Support",
          "Keyword: Stage / Hidden Heart",
        ],
        "combat.telemetry": [
          "Burst rhythm: Stable rotation",
          "Reaction lane: Vaporize / Electro-Charged",
          "Party impact: Sustained teamwide support",
          "Operator note: keep swap windows short",
        ],
        "memory.trace": [
          "She smiles first, then lets the silence speak.",
          "A brilliant stage, a tender core behind it.",
          "Fontaine remembers both the show and the heart.",
        ],
      },
    },
    heroImage:
      "./ImageReference/Furina/Png/elecpure_Furina_from_Genshin_Impact_dynamic_but_casual_full_bod_cc9b7414-353b-47d3-b2c5-74220bcb98e1 복사.png",
    immersiveImage:
      "./ImageReference/Furina/Png/elecpure_Furina_from_Genshin_Impact_dynamic_but_casual_full_bod_cc9b7414-353b-47d3-b2c5-74220bcb98e1 복사.png",
    immersiveBackdrop:
      "./ImageReference/Furina/elecpure_Furina_Genshin_Impact_hydro_archon_aesthetic_elegant_w_6456fe8e-9358-4d25-843b-03739edb85f3.png",
    immersiveWord: "FURINA",
    typography: {
      motto: "STAR OF FONTAINE • HIDDEN HEART",
      signature: "Salon Solitaire",
      displayFill1: "#f2fbff",
      displayFill2: "#a7deff",
      displayFill3: "#deefff",
      displayStroke: "rgba(214, 235, 255, 0.35)",
      displayGlow: "rgba(145, 219, 255, 0.44)",
      mottoColor: "rgba(223, 237, 255, 0.88)",
      signatureColor: "rgba(206, 227, 255, 0.68)",
      keywordTone: "rgba(212, 226, 255, 0.14)",
    },
    scrollFx: {
      beamOpacity: 0.62,
      causticOpacity: 0.34,
      beamSpread: 1,
    },
    immersiveKicker: "Hydro · Fontaine",
    immersiveIntroTitle: "About Furina",
    immersiveIntroBody:
      "관객이 보는 얼굴은 늘 완벽했지만, 그 미소 뒤에는 오래된 외로움이 숨어 있습니다. 푸리나는 무대 위의 화려함과 인간적인 다정함이 함께 빛나는 인물입니다.",
    immersiveDetailHeading: "Furina — Character Dossier",
    immersiveLore:
      "푸리나는 폰타인의 정의와 공연 문화가 겹쳐진 상징적인 인물입니다. 전투에서는 팀 버퍼로, 이야기에서는 가면 뒤의 진심으로 기억됩니다. 이 페이지는 그 두 얼굴을 '무대'라는 하나의 연출 언어로 연결합니다.",
    immersiveDecor: [
      {
        kind: "ribbon",
        label: "Vision",
        value: "HYDRO",
        x: "76%",
        y: "22%",
        r: "-3deg",
        w: "172px",
        px: 18,
        py: 10,
        bob: 8,
        speed: 0.8,
      },
      {
        kind: "metric",
        label: "Role",
        value: "파티 서포터",
        fill: "92%",
        x: "20%",
        y: "21%",
        r: "-4deg",
        w: "244px",
        px: -24,
        py: 14,
        bob: 11,
        speed: 0.68,
      },
      {
        kind: "quickicons",
        x: "82%",
        y: "56%",
        r: "-2deg",
        w: "72px",
        icons: ["headset", "camera", "sparkle", "plus"],
        px: 15,
        py: -12,
        bob: 10,
        speed: 0.78,
      },
      {
        kind: "glyph",
        label: "Keyword",
        value: "가면 뒤의 진심",
        x: "17%",
        y: "66%",
        r: "3deg",
        w: "222px",
        px: -14,
        py: -9,
        bob: 9,
        speed: 0.96,
      },
      {
        kind: "badge",
        label: "Vibe",
        value: "당당함 · 여린 마음",
        x: "73%",
        y: "82%",
        r: "-8deg",
        w: "186px",
        px: 14,
        py: -5,
        bob: 7,
        speed: 1.05,
      },
    ],
    immersiveKeywords: [
      {
        text: "Hydro Archon",
        x: "18%",
        y: "47%",
        r: "-4deg",
        size: "md",
        px: -18,
        py: 8,
        bob: 5,
        speed: 0.7,
      },
      {
        text: "FONTAINE",
        x: "75%",
        y: "15%",
        r: "1deg",
        size: "sm",
        px: 11,
        py: -6,
        bob: 4,
        speed: 1.06,
      },
      {
        text: "SALON SOLITAIRE",
        x: "74%",
        y: "48%",
        r: "2deg",
        size: "md",
        px: 15,
        py: 7,
        bob: 6,
        speed: 0.82,
      },
      {
        text: "가면 뒤의 진심",
        x: "29%",
        y: "78%",
        r: "-2deg",
        size: "sm",
        px: -10,
        py: 8,
        bob: 4,
        speed: 1.2,
      },
    ],
    immersiveFx: [
      {
        type: "star",
        x: "25%",
        y: "28%",
        size: "16px",
        opa: 0.84,
        px: -30,
        py: 12,
        bob: 9,
        speed: 0.8,
      },
      {
        type: "star",
        x: "64%",
        y: "19%",
        size: "12px",
        opa: 0.78,
        px: 18,
        py: -8,
        bob: 7,
        speed: 1.08,
      },
      {
        type: "orb",
        x: "80%",
        y: "39%",
        size: "34px",
        opa: 0.52,
        px: 22,
        py: -14,
        bob: 14,
        speed: 0.62,
      },
      {
        type: "ring",
        x: "68%",
        y: "33%",
        size: "44px",
        opa: 0.4,
        px: 15,
        py: -10,
        bob: 11,
        speed: 0.56,
      },
      {
        type: "drop",
        x: "34%",
        y: "35%",
        size: "18px",
        opa: 0.76,
        px: -16,
        py: 9,
        bob: 10,
        speed: 1.14,
      },
      {
        type: "drop",
        x: "57%",
        y: "61%",
        size: "20px",
        opa: 0.7,
        px: 13,
        py: -8,
        bob: 12,
        speed: 0.9,
      },
      {
        type: "star",
        x: "14%",
        y: "57%",
        size: "10px",
        opa: 0.65,
        px: -12,
        py: 6,
        bob: 8,
        speed: 1.28,
      },
    ],
    gallery: [
      "./ImageReference/Furina/Png/elecpure_Furina_from_Genshin_Impact_upper_body_anime_illustrati_a6f0cab1-0149-49df-abbf-4de4074be603 복사.png",
      "./ImageReference/Furina/elecpure_Furina_from_Genshin_Impact_close-up_anime_portrait_sof_1c813a4e-3a9e-4f7e-b726-4e1ce2d718a8.png",
      "./ImageReference/Furina/elecpure_Furina_Genshin_Impact_hydro_archon_aesthetic_elegant_w_4ccfb667-7efb-4fa6-9294-af218a0e4642.png",
    ],
  },
  nahida: {
    id: "nahida",
    displayName: "Nahida",
    element: "Dendro · Sumeru",
    title: "Little Archon of Wisdom",
    description:
      "작은 체구 안에 깊은 지혜와 따뜻함을 품은 수메르의 신. 나히다의 페이지는 포근한 빛, 숲의 생기, 그리고 위로의 분위기를 중심으로 구성합니다.",
    profileText:
      "나히다는 덴드로 원소 반응을 부드럽게 이어주는 핵심 캐릭터입니다. 전투에서는 팀의 흐름을 안정적으로 이어주고, 이야기에서는 조용하지만 단단한 마음으로 오래 기억됩니다.",
    pills: ["Dendro", "5★", "Catalyst", "Sumeru"],
    stats: [
      ["역할", "원소 반응 중심 서포터"],
      ["무기", "법구 (Catalyst)"],
      ["매력 포인트", "작은 몸에 담긴 큰 지혜"],
    ],
    snapshot: {
      kicker: "Combat Snapshot",
      heading: "Reaction Amplifier",
      summary:
        "나히다는 원소 반응 기반 조합의 완성도를 끌어올리는 핵심 서포터입니다. 안정적인 연결과 넓은 커버 범위로 팀의 전투 리듬을 부드럽게 만듭니다.",
      points: [
        ["강점", "반응 트리거 안정성 + 넓은 전장 대응"],
        ["추천 반응", "Dendro 중심 개화/격화 계열"],
        ["운영 팁", "초반 표식 정리 후 순환을 일정하게 유지"],
      ],
      tags: ["Dendro Core", "Reaction Engine", "Consistent Uptime"],
    },
    terminal: {
      title: "Nahida Deep Scan Console",
      prompt: "nahida@sumeru:~$",
      bridgeCaption: "Sumeru Archive · Dream Bloom",
      fileLabel: "NAHIDA_LINEART.ASC",
      checksum: "84-B1-6C-2A",
      bootLogs: [
        "[BOOT] Combat Snapshot uplink accepted",
        "[SYNC] Region profile loaded: Sumeru",
        "[LOAD] Queue: portrait, mapline, keyword-banner",
        "[DECODE] Runtime profile: balanced",
        "[READY] ASCII channel online",
      ],
      assets: {
        portrait: "./ImageReference/Nahida/Png/LineArt.png",
        mapline: "./ImageReference/Nahida/Png/MapLine.jpg",
      },
      sequence: ["portrait", "mapline", "portrait", "mapline"],
      sceneLabels: {
        portrait: "NAHIDA_PORTRAIT.ASC",
        mapline: "SUMERU_MAPLINE.ASC",
        banner: "SUMERU_SIGNAL.ASC",
      },
      banners: ["SUMERU", "DENDRO", "DREAM BLOOM"],
      tabs: {
        "boot.log": [
          "Session: NAHIDA TERMINAL V3",
          "Node: Sanctuary relay",
          "Protocol: Dendro-Luma stream",
          "Status: Decode-ready",
        ],
        "ascii.feed": [
          "Charset: .,:;=+*#%@",
          "Sampling: 124 cols / adaptive rows",
          "Edge blend: 32%",
          "Glitch budget: LOW (cinematic safe)",
        ],
        "dossier.sys": [
          "Name: Nahida",
          "Element: Dendro · Sumeru",
          "Role: Reaction Support",
          "Keyword: Wisdom / Comfort",
        ],
        "combat.telemetry": [
          "Burst rhythm: Continuous reaction loop",
          "Reaction lane: Bloom / Quicken",
          "Party impact: Stable trigger coverage",
          "Operator note: tag enemies early",
        ],
        "memory.trace": [
          "A quiet voice that reaches the deepest place.",
          "Small form, boundless insight and warmth.",
          "Sumeru blooms where her gaze lingers.",
        ],
      },
    },
    heroImage: "./ImageReference/Nahida/Png/FullShotPng.png",
    immersiveImage: "./ImageReference/Nahida/Png/FullShotPng.png",
    immersiveBackdrop: "./ImageReference/Nahida/Png/FullShotBackground.png",
    immersiveWord: "NAHIDA",
    typography: {
      motto: "DREAM OF WISDOM • BLOOM OF SUMERU",
      signature: "Buer",
      displayFill1: "#f4ffef",
      displayFill2: "#c8f3ab",
      displayFill3: "#e8ffd9",
      displayStroke: "rgba(210, 241, 197, 0.34)",
      displayGlow: "rgba(186, 236, 142, 0.44)",
      mottoColor: "rgba(231, 251, 219, 0.88)",
      signatureColor: "rgba(210, 239, 188, 0.68)",
      keywordTone: "rgba(208, 239, 184, 0.16)",
    },
    scrollFx: {
      beamOpacity: 0.56,
      causticOpacity: 0.3,
      beamSpread: 0.94,
    },
    immersiveKicker: "Dendro · Sumeru",
    immersiveIntroTitle: "About Nahida",
    immersiveIntroBody:
      "나히다는 조용한 말투로도 사람의 마음을 오래 붙잡는 힘이 있습니다. 부드러운 미소와 깊은 통찰이 함께 느껴지도록 숲의 빛을 닮은 연출로 구성했습니다.",
    immersiveDetailHeading: "Nahida — Character Dossier",
    immersiveLore:
      "나히다의 핵심은 공감, 지혜, 그리고 연결입니다. 이 페이지는 덴드로의 생명감과 몽환적인 수메르 감성을 한 화면에 담아, 보는 순간 편안하면서도 신비로운 인상을 전달합니다.",
    immersiveDecor: [
      {
        kind: "ribbon",
        label: "Vision",
        value: "DENDRO",
        x: "76%",
        y: "22%",
        r: "-3deg",
        w: "176px",
        px: 16,
        py: 10,
        bob: 8,
        speed: 0.82,
      },
      {
        kind: "metric",
        label: "Role",
        value: "원소 반응 서포터",
        fill: "90%",
        x: "20%",
        y: "21%",
        r: "-3deg",
        w: "248px",
        px: -22,
        py: 14,
        bob: 11,
        speed: 0.7,
      },
      {
        kind: "quickicons",
        x: "82%",
        y: "56%",
        r: "-2deg",
        w: "72px",
        icons: ["leaf", "book", "sprout", "plus"],
        px: 14,
        py: -12,
        bob: 10,
        speed: 0.8,
      },
      {
        kind: "glyph",
        label: "Keyword",
        value: "작은 몸, 깊은 지혜",
        x: "17%",
        y: "66%",
        r: "2deg",
        w: "220px",
        px: -12,
        py: -8,
        bob: 9,
        speed: 0.94,
      },
      {
        kind: "badge",
        label: "Vibe",
        value: "포근함 · 통찰력",
        x: "73%",
        y: "82%",
        r: "-7deg",
        w: "186px",
        px: 12,
        py: -5,
        bob: 7,
        speed: 1.04,
      },
    ],
    immersiveKeywords: [
      {
        text: "LORD KUSANALI",
        x: "18%",
        y: "47%",
        r: "-4deg",
        size: "md",
        px: -16,
        py: 8,
        bob: 5,
        speed: 0.72,
      },
      {
        text: "SUMERU",
        x: "75%",
        y: "15%",
        r: "1deg",
        size: "sm",
        px: 11,
        py: -6,
        bob: 4,
        speed: 1.05,
      },
      {
        text: "DREAM BLOOM",
        x: "74%",
        y: "48%",
        r: "2deg",
        size: "md",
        px: 14,
        py: 7,
        bob: 6,
        speed: 0.84,
      },
      {
        text: "작지만 가장 깊은 위로",
        x: "28%",
        y: "78%",
        r: "-2deg",
        size: "sm",
        px: -10,
        py: 8,
        bob: 4,
        speed: 1.18,
      },
    ],
    immersiveFx: [
      {
        type: "star",
        x: "25%",
        y: "28%",
        size: "16px",
        opa: 0.82,
        px: -26,
        py: 12,
        bob: 9,
        speed: 0.82,
      },
      {
        type: "star",
        x: "64%",
        y: "19%",
        size: "12px",
        opa: 0.76,
        px: 18,
        py: -8,
        bob: 7,
        speed: 1.06,
      },
      {
        type: "orb",
        x: "80%",
        y: "39%",
        size: "34px",
        opa: 0.5,
        px: 20,
        py: -12,
        bob: 14,
        speed: 0.62,
      },
      {
        type: "ring",
        x: "68%",
        y: "33%",
        size: "44px",
        opa: 0.38,
        px: 14,
        py: -10,
        bob: 11,
        speed: 0.58,
      },
      {
        type: "drop",
        x: "34%",
        y: "35%",
        size: "18px",
        opa: 0.72,
        px: -14,
        py: 9,
        bob: 10,
        speed: 1.1,
      },
      {
        type: "drop",
        x: "57%",
        y: "61%",
        size: "20px",
        opa: 0.66,
        px: 12,
        py: -8,
        bob: 12,
        speed: 0.92,
      },
    ],
    gallery: [
      "./ImageReference/Nahida/Png/UpperShot.png",
      "./ImageReference/Nahida/Png/elecpure_Nahida_from_Genshin_Impact_close-up_anime_portrait_sof_68f4ced4-2048-4d68-a353-882f52153551.png",
      "./ImageReference/Nahida/Png/FullShotBackground.png",
    ],
  },
};
